Repository PakizeBozkurt/hugsforbugs, pull requests merged in 2023-03, with the labels that each got.

#38 36 refactor make back-end more dry - Back/End - Pakize Bozkurt
  server/authEndpoint.js
  server/demo.txt
  server/utils/middleware.js
Labels: documentation, enhancement, Part2

#45 #10 see all availability - Micheale Andemariam
  client/src/components/AvailableTrainees.js
  client/src/components/CreateAvailability.js
  client/src/components/Login.js
  client/src/components/Logout.js
  client/src/components/Navigator.js
  client/src/components/SendEmail.js
  package.json
Labels: documentation

#42 added more specific validation for each form input in the register co…
  client/src/components/Login.js
  client/src/components/Register.js
Labels: new, nice to have

#39 Added the password visibility toggle to both login and register forms
  client/src/components/Login.js
  client/src/components/Register.js
Labels: enhancement

#51 18 form validation
  client/src/components/Register.js
  client/src/components/home.css
  client/src/pages/Home.css
Labels: help wanted

#57 #55 -navbar and releated component added-Nagehan
  client/src/components/Heading.js
  client/src/components/Home.js
  client/src/components/Subheading.js
Labels: high priority

#58 #46-footer- Footer Component- Pakize Bozkurt
  client/src/App.js
  client/src/components/CreateAvailability.js
  client/src/components/Footer/Footer.js
  client/src/components/Footer/footer.css
  client/src/components/Home.js
  client/src/components/Login.js
  client/src/components/MyAvailability.js
  client/src/components/Register.js
  package-lock.json
  package.json
Labels: documentation, high priority

#67 66 style the login page
  client/src/components/Footer/footer.css
  client/src/components/Home.js
  client/src/components/Login.js
  client/src/components/MyAvailability.js
  client/src/components/NavBar.js
  client/src/components/Register.js
  client/src/index.html
  client/src/register.css
  package-lock.json
Labels: enhancement

#60 #33 content components refactor - Pakize Bozkurt
  client/src/components/Heading.js
  client/src/components/Home.js
  client/src/components/Subheading.js
  client/src/components/content.js
Labels: invalid, new, nice to have

#77 Removing dependabot.yml - Pakize Bozkurt
  .github/dependabot.yml
Labels: help wanted

#82 80 search functionality - Micheale Andemariam
  client/src/components/AllUsers.js
  client/src/components/AvailableTrainees.js
  client/src/components/Login.js
  client/src/components/NavBar.js
  client/src/components/Navigator.js
  client/src/components/Register.js
  client/src/components/ResultPage.js
  client/src/components/main.css
Labels: bug, documentation, enhancement

#84 81 update edit delete button - Micheale Andemariam
  client/src/components/DeleteMyAvailability.js
  client/src/components/EditMyAvailability.js
Labels: enhancement, nice to have

#83 69 create my availability cards - Micheale Andemariam
  .github/dependabot.yml
  client/src/components/AvailableTrainees.js
  client/src/components/CreateAvailability.js
  client/src/components/MyAvailability.js
  client/src/components/MyAvailabilityCards.js
  client/src/components/NavBar.js
  client/src/components/Navigator.js
Labels: enhancement, nice to have, high priority

#93 #86-footer-styles-and-responsivness- Pakize-Bozkurt
  client/src/components/AllUsers.js
  client/src/components/AvailabilityCards.js
  client/src/components/AvailableTrainees.js
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
  client/src/components/Footer/footer.css
  client/src/components/MyAvailability.js
  client/src/components/Navigator.js
  client/src/components/ResultPage.js
  server/emailsending.js
Labels: bug, nice to have

#94 #87-navbar update-Nagehan
  client/src/components/NavBar.js
  client/src/components/UserInfoMenu.js
Labels: enhancement

#101 #98-email-sending-bug - Pakize Bozkurt
  server/authEndpoint.js
  server/emailsending.js
Labels: bug

#102 #91 back end moverefactor endpoints - Pakize Bozkurt
  client/src/App.js
  client/src/components/AllUsers.js
  client/src/components/AvailabilityCards.js
  client/src/components/AvailableTrainees.js
  client/src/components/CreateAvailability.js
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
  client/src/components/Heading.css
  client/src/components/Home.js
  client/src/components/Login.js
  client/src/components/Logout.js
  client/src/components/NavBar.js
  client/src/components/Navigator.js
  client/src/components/Register.css
  client/src/components/Register.js
  client/src/components/ResultPage.js
  client/src/components/SendEmail.js
  client/src/components/UserInfoMenu.js
  client/src/components/UserProfile.js
  client/src/components/availabilityCards.css
  client/src/components/main.css
Labels: bug, help wanted

#108 #107-logout-fixing - Pakize Bozkurt
  client/src/components/Logout.js
Labels: bug, help wanted, high priority

#113 112-footer-bug fixing - Pakize Bozkurt
  client/src/components/Footer/Footer.js
  client/src/components/NavBar.js
  client/src/components/Register.js
  client/src/logo.svg
Labels: bug, help wanted, high priority
